### PR TITLE
Fixing Python 3.7 incompatibility with async keywords

### LINKED ISSUE #40: Not compatible with Python37 - async is now a keyword
There are several places where the name `async` has been used as a variable name. Since this is now a keyword in Python37, the interpreter will send a SyntaxError.

@jmarinllao will send a PR soon :)

### PR DESCRIPTION
**Pull request by jmarinllao**
closes #40 
Even though was fixed the async problem, there is still a problem with gevent.

### CODE REVIEW

**Comment by nhstanley** [comment]
FYI, this works for me with python3.7. Further, the failing Travis test seems to be because the python3.6 test isn't actually testing python3.6, but bizarrely python2.7.

**Comment by eloyfelix** [comment]
thanks for this but because we are dropping the old webservices resources (CompoundResource, TargetResource...) and Py2 compatibility this PR won't be necessary.

**Comment by naefl** [comment]
Hey @eloyfelix.

I still get the error

`File "/opt/conda/lib/python3.7/site-packages/chembl_webresource_client/web_resource.py", line 184
    def _get_one(self, url, async, frmt, method='get', data=None):`

`python 3.7.4`

`chembl-webresource-client 0.9.31`

**Comment by eloyfelix** [comment]
Hi naefl, we didn't updated yet the packages in pip and conda. If you want to try the changes in the repo you can install the package from the master branch

```
pip install https://github.com/chembl/chembl_webresource_client/archive/master.zip
```

**Comment by eloyfelix** [comment]
New version is already available in pypi: https://pypi.org/project/chembl-webresource-client/

so it can be installed from it:
```
pip install chembl-webresource-client
```

**Pull request closed without merging**
